# Generated by Django 4.1.2 on 2022-11-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_tiporendimento_alter_investimento_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimento',
            name='cotas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
