# Generated by Django 4.1.2 on 2022-11-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_investimento_cotas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
