# Generated by Django 4.1.2 on 2022-11-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_variavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variavel',
            name='valor',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
