# Generated by Django 4.1.2 on 2022-11-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_variavel_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variavel',
            name='valor',
        ),
        migrations.CreateModel(
            name='VariavelMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('data_criacao', models.DateTimeField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.variavel')),
            ],
        ),
        migrations.CreateModel(
            name='CalculoFuturo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.investimento')),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.variavel')),
            ],
        ),
    ]
