# Generated by Django 4.1.2 on 2022-11-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_variavel_valor_variavelmes_calculofuturo'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculofuturo',
            name='bonus',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
