# Generated by Django 4.1.2 on 2022-11-13 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_tipoinvestimentosemideiadenome_variavel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariavelImposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.variavel')),
            ],
        ),
    ]
