# Generated by Django 4.1.2 on 2022-12-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_variavelimposto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investimento',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='investimento',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investimento',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
