# Generated by Django 4.1.2 on 2022-12-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_investimento_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculofuturo',
            name='soma',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
